language: rust
matrix:
  fast_finish: true
  include:
    - rust: stable
      before_script:
        - rustup component add clippy
    - rust: beta
      before_script:
        - rustup component add clippy
    - rust: nightly
      before_script:
        - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
      allow_failures: true
sudo: true
addons:
  apt:
    packages:
      - libgsl0-dev
branches:
  only:
    - master
script:
  - cargo clippy --all-targets --all-features
  - cargo build
  - cargo test
