language: rust
rust:
  - stable
fast_finish: true
sudo: true
addons:
  apt:
    packages:
      - libgsl0-dev
branches:
  only:
    - master
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features
  - cargo build
  - cargo test
